//! Temporary variables phase.
//!
//! Find all assignments and usages of temporary variables, which are linked to each other with
//! cross-references. Generate names for each cross-reference, and add a `DeclareVarStmt` to
//! initialize them at the beginning of the update block.
//!
//! Temporary variables are generated by the `expand_safe_reads` phase when the guard expression
//! has side effects (e.g., function calls) and needs to avoid re-evaluation:
//!
//! ```text
//! a?.foo()?.b
//! ↓
//! (tmp_0_0 = a?.foo(), tmp_0_0 == null ? null : tmp_0_0.b)
//! ```
//!
//! ## Name Generation
//!
//! Names are generated using the pattern `tmp_{opIndex}_{count}`. Names can be reused after
//! the final read of a variable, allowing for efficient variable reuse in complex expressions.
//!
//! ## Name Reuse Algorithm
//!
//! TypeScript uses a two-pass algorithm (lines 38-74 of temporary_variables.ts):
//!
//! 1. **First pass**: Find the "final read" for each xref (the last `ReadTemporaryExpr` for each xref)
//! 2. **Second pass**: When the final read is encountered, decrement the counter to allow reuse
//!
//! For example, with `cipher()?.isDeleted && !cipher()?.edit`:
//! - Both safe navigations share `tmp_4_0` because after the first expression's final read,
//!   the counter decrements and the name becomes available for reuse.
//!
//! Ported from Angular's `template/pipeline/src/phases/temporary_variables.ts`.

use std::cell::RefCell;

use oxc_allocator::Allocator;
use oxc_span::Atom;
use rustc_hash::{FxHashMap, FxHashSet};

use crate::ir::expression::{
    IrExpression, VisitorContextFlag, transform_expressions_in_create_op,
    transform_expressions_in_expression, transform_expressions_in_update_op,
    visit_expressions_in_create_op, visit_expressions_in_expression,
    visit_expressions_in_update_op,
};
use crate::ir::list::{CreateOpList, UpdateOpList};
use crate::ir::ops::{
    CreateOp, CreateOpBase, CreateStatementOp, StatementOp, UpdateOp, UpdateOpBase, XrefId,
};
use crate::output::ast::{DeclareVarStmt, OutputStatement, StmtModifier};
use crate::pipeline::compilation::{ComponentCompilationJob, HostBindingCompilationJob};

/// Generates temporary variable names and declarations.
///
/// This phase:
/// 1. Finds all `AssignTemporaryExpr` and `ReadTemporaryExpr` in the IR
/// 2. Assigns unique names to each temp variable (format: `tmp_{opIndex}_{count}`)
/// 3. Generates `DeclareVarStmt` operations and prepends them to the create and update blocks
///
/// This also recursively processes handler_ops for Listener, AnimationListener, and TwoWayListener,
/// as well as track_by_ops for RepeaterCreate operations.
pub fn generate_temporary_variables(job: &mut ComponentCompilationJob<'_>) {
    let allocator = job.allocator;

    // Process all views - both create and update ops (matching TypeScript behavior)
    for view in job.all_views_mut() {
        let mut create_stmts = generate_temporaries_for_create(&mut view.create, allocator);
        view.create.prepend(&mut create_stmts);

        let mut update_stmts = generate_temporaries_for_update(&mut view.update, allocator);
        view.update.prepend(&mut update_stmts);
    }
}

/// Generates temporary variable declarations for create operations.
/// Returns a list of CreateStatementOps to prepend to the create list.
///
/// Also recursively processes handler_ops for Listener, AnimationListener, and TwoWayListener,
/// and track_by_ops for RepeaterCreate operations.
fn generate_temporaries_for_create<'a>(
    ops: &mut CreateOpList<'a>,
    allocator: &'a Allocator,
) -> CreateOpList<'a> {
    let mut op_count = 0;
    let mut generated_statements = CreateOpList::new(allocator);

    for op in ops.iter_mut() {
        // Pass 1: Count reads per xref to determine final reads
        let read_counts = RefCell::new(FxHashMap::<XrefId, usize>::default());
        visit_expressions_in_create_op(
            op,
            &|expr, flags| {
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                if let IrExpression::ReadTemporary(read) = expr {
                    *read_counts.borrow_mut().entry(read.xref).or_insert(0) += 1;
                }
            },
            VisitorContextFlag::NONE,
        );
        let total_reads = read_counts.into_inner();

        // Pass 2: Assign names with reuse when final read is encountered
        let tracker = RefCell::new(TempVarTracker::new(op_count, total_reads));

        transform_expressions_in_create_op(
            op,
            &|expr, flags| {
                // Skip child operations (like handler_ops) - they're processed separately
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                assign_temp_names(expr, &tracker, allocator);
            },
            VisitorContextFlag::NONE,
        );

        // Collect unique names and create declarations
        let defs = tracker.into_inner().defs;
        for name in collect_unique_names(&defs) {
            let stmt = create_declare_var_statement(allocator, &name);
            generated_statements.push(CreateOp::Statement(CreateStatementOp {
                base: CreateOpBase::default(),
                statement: stmt,
            }));
        }

        op_count += 1;

        // Recursively process handler_ops for Listener, AnimationListener, and TwoWayListener.
        // This matches TypeScript's behavior where generateTemporaries is called recursively
        // for nested ops lists and the results are prepended to those lists.
        match op {
            CreateOp::Listener(listener) => {
                // Process handler_ops and handler_expression together.
                // In Angular TS, the handler_expression is part of handlerOps.
                // In our IR, it's a separate field, so we must include it in
                // temporary variable processing to generate the correct `let tmp_N_0;`
                // declarations inside the listener function.
                let mut handler_stmts = generate_temporaries_for_handler_ops_with_expression(
                    &mut listener.handler_ops,
                    &mut listener.handler_expression,
                    allocator,
                );
                prepend_update_ops(&mut listener.handler_ops, &mut handler_stmts, allocator);
            }
            CreateOp::AnimationListener(listener) => {
                let mut handler_stmts =
                    generate_temporaries_for_handler_ops(&mut listener.handler_ops, allocator);
                prepend_update_ops(&mut listener.handler_ops, &mut handler_stmts, allocator);
            }
            CreateOp::TwoWayListener(listener) => {
                let mut handler_stmts =
                    generate_temporaries_for_handler_ops(&mut listener.handler_ops, allocator);
                prepend_update_ops(&mut listener.handler_ops, &mut handler_stmts, allocator);
            }
            CreateOp::RepeaterCreate(repeater) => {
                // Process track_by_ops if present
                if let Some(track_by_ops) = &mut repeater.track_by_ops {
                    let mut track_stmts =
                        generate_temporaries_for_handler_ops(track_by_ops, allocator);
                    prepend_update_ops(track_by_ops, &mut track_stmts, allocator);
                }
            }
            _ => {}
        }
    }

    generated_statements
}

/// Generates temporary variable declarations for handler_ops (which are Vec<UpdateOp>).
/// This is used for Listener, AnimationListener, TwoWayListener handler_ops and
/// RepeaterCreate track_by_ops.
fn generate_temporaries_for_handler_ops<'a>(
    ops: &mut [UpdateOp<'a>],
    allocator: &'a Allocator,
) -> Vec<UpdateOp<'a>> {
    let mut op_count = 0;
    let mut generated_statements = Vec::new();

    for op in ops.iter_mut() {
        // Pass 1: Count reads per xref to determine final reads
        let read_counts = RefCell::new(FxHashMap::<XrefId, usize>::default());
        visit_expressions_in_update_op(
            op,
            &|expr, flags| {
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                if let IrExpression::ReadTemporary(read) = expr {
                    *read_counts.borrow_mut().entry(read.xref).or_insert(0) += 1;
                }
            },
            VisitorContextFlag::NONE,
        );
        let total_reads = read_counts.into_inner();

        // Pass 2: Assign names with reuse when final read is encountered
        let tracker = RefCell::new(TempVarTracker::new(op_count, total_reads));

        transform_expressions_in_update_op(
            op,
            &|expr, flags| {
                // Skip child operations - they're processed separately
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                assign_temp_names(expr, &tracker, allocator);
            },
            VisitorContextFlag::NONE,
        );

        // Collect unique names and create declarations
        let defs = tracker.into_inner().defs;
        for name in collect_unique_names(&defs) {
            let stmt = create_declare_var_statement(allocator, &name);
            generated_statements.push(UpdateOp::Statement(StatementOp {
                base: UpdateOpBase::default(),
                statement: stmt,
            }));
        }

        op_count += 1;
    }

    generated_statements
}

/// Generates temporary variable declarations for handler_ops AND handler_expression together.
///
/// In Angular TS, the handler_expression is part of handlerOps (there is no separate field).
/// In our IR, handler_expression is a separate field on ListenerOp. We must include it in
/// temporary variable processing so that `let tmp_N_0;` declarations are generated inside
/// the listener function scope rather than the parent create scope.
///
/// The handler_ops are processed first (same as `generate_temporaries_for_handler_ops`),
/// then handler_expression is processed once AFTER the loop with op_count equal to
/// handler_ops.len(). This matches Angular TS where the return expression is the last
/// entry in handlerOps at index N.
fn generate_temporaries_for_handler_ops_with_expression<'a>(
    ops: &mut [UpdateOp<'a>],
    handler_expression: &mut Option<oxc_allocator::Box<'a, IrExpression<'a>>>,
    allocator: &'a Allocator,
) -> Vec<UpdateOp<'a>> {
    // First, process handler_ops exactly like generate_temporaries_for_handler_ops
    let mut generated_statements = generate_temporaries_for_handler_ops(ops, allocator);

    // Then process handler_expression once, with op_count = ops.len().
    // In Angular TS, the return expression is the last entry in handlerOps,
    // so its op index equals the number of preceding ops.
    if let Some(handler_expr) = handler_expression.as_mut() {
        let op_count = ops.len();

        // Pass 1: Count reads per xref to determine final reads
        let read_counts = RefCell::new(FxHashMap::<XrefId, usize>::default());
        visit_expressions_in_expression(
            handler_expr,
            &|expr, flags| {
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                if let IrExpression::ReadTemporary(read) = expr {
                    *read_counts.borrow_mut().entry(read.xref).or_insert(0) += 1;
                }
            },
            VisitorContextFlag::NONE,
        );
        let total_reads = read_counts.into_inner();

        // Pass 2: Assign names with reuse when final read is encountered
        let tracker = RefCell::new(TempVarTracker::new(op_count, total_reads));
        transform_expressions_in_expression(
            handler_expr,
            &|expr, flags| {
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                assign_temp_names(expr, &tracker, allocator);
            },
            VisitorContextFlag::NONE,
        );

        // Collect unique names and create declarations
        let defs = tracker.into_inner().defs;
        for name in collect_unique_names(&defs) {
            let stmt = create_declare_var_statement(allocator, &name);
            generated_statements.push(UpdateOp::Statement(StatementOp {
                base: UpdateOpBase::default(),
                statement: stmt,
            }));
        }
    }

    generated_statements
}

/// Prepends generated statement ops to a handler_ops Vec.
/// Since handler_ops is a Vec (not OpList), we need to handle prepending manually.
fn prepend_update_ops<'a>(
    ops: &mut oxc_allocator::Vec<'a, UpdateOp<'a>>,
    stmts: &mut Vec<UpdateOp<'a>>,
    allocator: &'a Allocator,
) {
    if stmts.is_empty() {
        return;
    }

    // Create a new vec with capacity for both stmts and ops
    let mut new_ops = oxc_allocator::Vec::with_capacity_in(stmts.len() + ops.len(), allocator);

    // Add statement ops first (prepend)
    for stmt in stmts.drain(..) {
        new_ops.push(stmt);
    }

    // Then add the original ops
    for op in ops.drain(..) {
        new_ops.push(op);
    }

    // Replace the original vec
    *ops = new_ops;
}

/// Generates temporary variable declarations for update operations.
/// Returns a list of StatementOps to prepend to the update list.
fn generate_temporaries_for_update<'a>(
    ops: &mut UpdateOpList<'a>,
    allocator: &'a Allocator,
) -> UpdateOpList<'a> {
    let mut op_count = 0;
    let mut generated_statements = UpdateOpList::new(allocator);

    for op in ops.iter_mut() {
        // Pass 1: Count reads per xref to determine final reads
        let read_counts = RefCell::new(FxHashMap::<XrefId, usize>::default());
        visit_expressions_in_update_op(
            op,
            &|expr, flags| {
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                if let IrExpression::ReadTemporary(read) = expr {
                    *read_counts.borrow_mut().entry(read.xref).or_insert(0) += 1;
                }
            },
            VisitorContextFlag::NONE,
        );
        let total_reads = read_counts.into_inner();

        // Pass 2: Assign names with reuse when final read is encountered
        let tracker = RefCell::new(TempVarTracker::new(op_count, total_reads));

        transform_expressions_in_update_op(
            op,
            &|expr, flags| {
                // Skip child operations (like handler_ops) - they're processed separately
                if flags.contains(VisitorContextFlag::IN_CHILD_OPERATION) {
                    return;
                }
                assign_temp_names(expr, &tracker, allocator);
            },
            VisitorContextFlag::NONE,
        );

        // Collect unique names and create declarations
        let defs = tracker.into_inner().defs;
        for name in collect_unique_names(&defs) {
            let stmt = create_declare_var_statement(allocator, &name);
            generated_statements.push(UpdateOp::Statement(StatementOp {
                base: UpdateOpBase::default(),
                statement: stmt,
            }));
        }

        op_count += 1;
    }

    generated_statements
}

/// Creates a DeclareVarStmt without an initializer.
/// This matches Angular's behavior for temp variable declarations: `var tmp_X_Y;`
/// Note: Angular uses `var` (not `const`) for uninitialized temp variables.
/// See: packages/compiler/src/output/abstract_js_emitter.ts line 6760
fn create_declare_var_statement<'a>(allocator: &'a Allocator, name: &str) -> OutputStatement<'a> {
    OutputStatement::DeclareVar(oxc_allocator::Box::new_in(
        DeclareVarStmt {
            name: Atom::from(allocator.alloc_str(name)),
            value: None,
            modifiers: StmtModifier::NONE, // Use `var` since there's no initializer
            leading_comment: None,
            source_span: None,
        },
        allocator,
    ))
}

/// Collect unique names from defs map, sorted for deterministic output.
fn collect_unique_names(defs: &FxHashMap<XrefId, String>) -> Vec<String> {
    let mut seen = FxHashSet::default();
    let mut names: Vec<_> = defs.values().filter(|v| seen.insert(*v)).cloned().collect();
    // Sort for deterministic output (TypeScript uses Set which has insertion order)
    names.sort();
    names
}

/// Assigns names to temporary variable expressions.
fn assign_temp_names<'a>(
    expr: &mut IrExpression<'a>,
    tracker: &RefCell<TempVarTracker>,
    allocator: &'a Allocator,
) {
    match expr {
        IrExpression::AssignTemporary(assign) => {
            let name = tracker.borrow_mut().assign(assign.xref);
            assign.name = Some(Atom::from(allocator.alloc_str(&name)));
        }
        IrExpression::ReadTemporary(read) => {
            let name = tracker.borrow_mut().read(read.xref);
            if let Some(n) = name {
                read.name = Some(Atom::from(allocator.alloc_str(&n)));
            }
        }
        // Recursively process nested expressions
        IrExpression::SafeTernary(st) => {
            assign_temp_names(&mut st.guard, tracker, allocator);
            assign_temp_names(&mut st.expr, tracker, allocator);
        }
        IrExpression::Ternary(t) => {
            assign_temp_names(&mut t.condition, tracker, allocator);
            assign_temp_names(&mut t.true_expr, tracker, allocator);
            assign_temp_names(&mut t.false_expr, tracker, allocator);
        }
        IrExpression::SafePropertyRead(sp) => {
            assign_temp_names(&mut sp.receiver, tracker, allocator);
        }
        IrExpression::SafeKeyedRead(sk) => {
            assign_temp_names(&mut sk.receiver, tracker, allocator);
            assign_temp_names(&mut sk.index, tracker, allocator);
        }
        IrExpression::SafeInvokeFunction(sf) => {
            assign_temp_names(&mut sf.receiver, tracker, allocator);
            for arg in sf.args.iter_mut() {
                assign_temp_names(arg, tracker, allocator);
            }
        }
        IrExpression::PipeBinding(pb) => {
            for arg in pb.args.iter_mut() {
                assign_temp_names(arg, tracker, allocator);
            }
        }
        IrExpression::PipeBindingVariadic(pbv) => {
            assign_temp_names(&mut pbv.args, tracker, allocator);
        }
        IrExpression::PureFunction(pf) => {
            for arg in pf.args.iter_mut() {
                assign_temp_names(arg, tracker, allocator);
            }
        }
        IrExpression::Interpolation(i) => {
            for e in i.expressions.iter_mut() {
                assign_temp_names(e, tracker, allocator);
            }
        }
        IrExpression::RestoreView(rv) => {
            use crate::ir::expression::RestoreViewTarget;
            if let RestoreViewTarget::Dynamic(e) = &mut rv.view {
                assign_temp_names(e, tracker, allocator);
            }
        }
        IrExpression::ResetView(rv) => {
            assign_temp_names(&mut rv.expr, tracker, allocator);
        }
        IrExpression::ConditionalCase(cc) => {
            if let Some(e) = &mut cc.expr {
                assign_temp_names(e, tracker, allocator);
            }
        }
        IrExpression::TwoWayBindingSet(tbs) => {
            assign_temp_names(&mut tbs.target, tracker, allocator);
            assign_temp_names(&mut tbs.value, tracker, allocator);
        }
        IrExpression::StoreLet(sl) => {
            assign_temp_names(&mut sl.value, tracker, allocator);
        }
        IrExpression::ConstCollected(cc) => {
            assign_temp_names(&mut cc.expr, tracker, allocator);
        }
        IrExpression::Binary(binary) => {
            assign_temp_names(&mut binary.lhs, tracker, allocator);
            assign_temp_names(&mut binary.rhs, tracker, allocator);
        }
        IrExpression::ResolvedPropertyRead(rpr) => {
            assign_temp_names(&mut rpr.receiver, tracker, allocator);
        }
        IrExpression::ResolvedBinary(rb) => {
            assign_temp_names(&mut rb.left, tracker, allocator);
            assign_temp_names(&mut rb.right, tracker, allocator);
        }
        IrExpression::ResolvedCall(rc) => {
            assign_temp_names(&mut rc.receiver, tracker, allocator);
            for arg in rc.args.iter_mut() {
                assign_temp_names(arg, tracker, allocator);
            }
        }
        IrExpression::ResolvedKeyedRead(rkr) => {
            assign_temp_names(&mut rkr.receiver, tracker, allocator);
            assign_temp_names(&mut rkr.key, tracker, allocator);
        }
        IrExpression::ResolvedSafePropertyRead(rspr) => {
            assign_temp_names(&mut rspr.receiver, tracker, allocator);
        }
        IrExpression::DerivedLiteralArray(arr) => {
            for entry in arr.entries.iter_mut() {
                assign_temp_names(entry, tracker, allocator);
            }
        }
        IrExpression::DerivedLiteralMap(map) => {
            for value in map.values.iter_mut() {
                assign_temp_names(value, tracker, allocator);
            }
        }
        IrExpression::LiteralArray(arr) => {
            for elem in arr.elements.iter_mut() {
                assign_temp_names(elem, tracker, allocator);
            }
        }
        IrExpression::LiteralMap(map) => {
            for value in map.values.iter_mut() {
                assign_temp_names(value, tracker, allocator);
            }
        }
        // Leaf expressions - no nested expressions
        IrExpression::LexicalRead(_)
        | IrExpression::Reference(_)
        | IrExpression::Context(_)
        | IrExpression::NextContext(_)
        | IrExpression::GetCurrentView(_)
        | IrExpression::ReadVariable(_)
        | IrExpression::PureFunctionParameter(_)
        | IrExpression::Empty(_)
        | IrExpression::SlotLiteral(_)
        | IrExpression::ConstReference(_)
        | IrExpression::ContextLetReference(_)
        | IrExpression::TrackContext(_)
        | IrExpression::ExpressionRef(_)
        | IrExpression::Ast(_)
        | IrExpression::OutputExpr(_) => {
            // No nested IR expressions to process
            // Note: Ast expressions contain AngularExpression which doesn't have
            // AssignTemporary/ReadTemporary - those only exist at the IR level
        }
        IrExpression::Not(n) => {
            assign_temp_names(&mut n.expr, tracker, allocator);
        }
        IrExpression::Unary(u) => {
            assign_temp_names(&mut u.expr, tracker, allocator);
        }
        IrExpression::Typeof(t) => {
            assign_temp_names(&mut t.expr, tracker, allocator);
        }
        IrExpression::Void(v) => {
            assign_temp_names(&mut v.expr, tracker, allocator);
        }
        IrExpression::ResolvedTemplateLiteral(rtl) => {
            for e in rtl.expressions.iter_mut() {
                assign_temp_names(e, tracker, allocator);
            }
        }

        IrExpression::ArrowFunction(arrow_fn) => {
            assign_temp_names(&mut arrow_fn.body, tracker, allocator);
        }
        IrExpression::Parenthesized(paren) => {
            assign_temp_names(&mut paren.expr, tracker, allocator);
        }
    }
}

// ============================================================================
// Supporting Types
// ============================================================================

/// Tracks temporary variable assignment state with name reuse support.
///
/// Implements TypeScript's two-pass algorithm where:
/// 1. First pass collects total reads per xref
/// 2. Second pass assigns names and decrements counter on final read for reuse
#[derive(Debug)]
struct TempVarTracker {
    /// Current operation index for generating names.
    op_index: usize,
    /// Current counter for generating unique names. Can go down when names are released.
    count: usize,
    /// Set of XrefIds that have been assigned a name.
    assigned: FxHashSet<XrefId>,
    /// Set of XrefIds that have been released (final read encountered).
    released: FxHashSet<XrefId>,
    /// Map from XrefId to generated variable name.
    defs: FxHashMap<XrefId, String>,
    /// Total number of reads per xref (from first pass).
    total_reads: FxHashMap<XrefId, usize>,
    /// Current read count per xref (incremented during second pass).
    current_reads: FxHashMap<XrefId, usize>,
}

impl TempVarTracker {
    /// Creates a new tracker for the given operation index with read counts from first pass.
    fn new(op_index: usize, total_reads: FxHashMap<XrefId, usize>) -> Self {
        Self {
            op_index,
            count: 0,
            assigned: FxHashSet::default(),
            released: FxHashSet::default(),
            defs: FxHashMap::default(),
            total_reads,
            current_reads: FxHashMap::default(),
        }
    }

    /// Assigns a name to a temporary variable if not already assigned.
    ///
    /// Returns the assigned name.
    fn assign(&mut self, xref: XrefId) -> String {
        if !self.assigned.contains(&xref) {
            self.assigned.insert(xref);
            let name = format!("tmp_{}_{}", self.op_index, self.count);
            self.count += 1;
            self.defs.insert(xref, name.clone());
            name
        } else {
            self.defs.get(&xref).cloned().unwrap_or_default()
        }
    }

    /// Gets the name for a temporary variable read.
    /// Also checks if this is the final read and releases the name for reuse.
    fn read(&mut self, xref: XrefId) -> Option<String> {
        let name = self.defs.get(&xref).cloned();

        // Track read count and check if this is the final read
        let current = self.current_reads.entry(xref).or_insert(0);
        *current += 1;

        if let Some(total) = self.total_reads.get(&xref) {
            if *current == *total && !self.released.contains(&xref) {
                // This is the final read - release the name for reuse
                self.released.insert(xref);
                if self.count > 0 {
                    self.count -= 1;
                }
            }
        }

        name
    }
}

/// Generates temporary variables for host binding compilation.
///
/// Host version - only processes the root unit (no embedded views).
/// Processes both create and update ops to match TypeScript behavior.
pub fn generate_temporary_variables_for_host(job: &mut HostBindingCompilationJob<'_>) {
    let allocator = job.allocator;

    let mut create_stmts = generate_temporaries_for_create(&mut job.root.create, allocator);
    job.root.create.prepend(&mut create_stmts);

    let mut update_stmts = generate_temporaries_for_update(&mut job.root.update, allocator);
    job.root.update.prepend(&mut update_stmts);
}
